### ISSUE TITLE
Provide Docker images for Gauge itself

### ISSUE THREAD

**Issue by x80486** [getgauge/infrastructure#3]
I think it will be great to have Docker images that provides `Gauge` out-of-the-box.

For example, you would create a base image and then use it to create the others in order to support the different language plugins. In the end, the tagging would be a number, corresponding to the actual `Gauge` version and later on you can choose a _term_ in order to account for the rest of the plugins – read: reporting and "other" plugins. Probably this can be skipped, or just install the most used ones.

This would save time on doing these steps all the time:

```dockerfile
FROM golang:1.12.9-stretch

WORKDIR /tmp/workspace/

ADD https://github.com/getgauge/gauge/releases/download/v1.0.5/gauge-1.0.5-linux.x86_64.zip ./

COPY . ./

RUN set -xe \
  && apt-get update \
  && apt-get install -q -y unzip \
  && unzip -o gauge-1.0.5-linux.x86_64.zip -d /usr/local/bin \
  && gauge install html-report --version 4.0.8 \
  && gauge install go --version 0.1.3
```

---

**UPDATE**

In case you consider this one, I think the _reporting and "other" plugins_ part could be ignored; looks like for any `Gauge` project, once `Gauge` is installed, one would only need to run `gauge install` (inside the project's subdirectory) and all the plugins used by that project will be installed – probably from `manifest.json`. Although if that's the case, it's impossible to pin the version(s), or at least I don't see a way to specify that.

**Comment by sriv** [comment]
@x80486 we considered this a while back, and as you have mentioned it is quite simple given gauge is a single binary. 

We figured the complexity is not in publishing the gauge image, rather in the additional runtimes required. For instance, your example uses a `golang` base image, but gauge could be used with java/c#/ruby/javascript/python/golang and each of these have versions which may or may not have backward compatibility. And language runtime version managers such as `rvm`, `nvm` or `gimme` tend to make the images mutable.

And given all the above are moving targets, we need to be able to support all versions possible. The permutation seemed too high for the value it would bring. 

Plugins come with their own permutation problem, like you say, but a little less complicated than the language runtimes. 

Instead, we recommend users drop a version of gauge into an image of their choice. Does that make sense?

**Comment by x80486** [comment]
I understand. I know you support several languages and the permutations can make this difficult :sunglasses:
